using System.Text;
using azuki_project;

public class Gui_sim {

    // StringBuilder cwln = new StringBuilder();
    // StringBuilder window_sb = new StringBuilder();
    // public void insert_cursor() {
    //     Console.WriteLine("abcdefg");
    //     Console.WriteLine("// value before: abcdefg");
    //     Console.SetCursorPosition(0, 0);
    //     Console.WriteLine("123");

    //     String cursor = Console.ReadLine();
    // }

    // public void TextBox(int line, int col, string text) {
    //     Console.SetCursorPosition(col, line);
    //     Console.WriteLine(text);
    // }
    // public void Box(int line, int col, string text) {
    //     Console.SetCursorPosition(col, line);
    //     Console.Write("_");
    //     int len = text.Length;
    //     for (int a = 0; a < (len + 2); a++) {
    //         Console.Write("_");
    //     }
    //     Console.WriteLine("_");

    //     Console.SetCursorPosition(col, line + 1);
    //     Console.WriteLine("| " + text + " |");


    //     Console.SetCursorPosition(col, line + 2);
    //     Console.Write("‾");
    //     for (int a = 0; a < (len + 2); a++) {
    //         Console.Write("‾");
    //     }
    //     Console.WriteLine("‾");

    // }

    // public void Icon(string[] icon, int selector, int line, int col) {
    //     // program
    //     // List<string> icon_ = new List<string>();
    //     foreach (var printline in icon) {
    //         Console.SetCursorPosition(col, line);
    //         Console.Write(Program.Pointer == selector ? Program.BLACK_ON_WHITE : Program.WHITE_ON_BLACK);
    //         Console.Write(printline);
    //         Console.Write(Program.WHITE_ON_BLACK);
    //         line++;
    //     }
    // }
    
    
    // public void Window(string[] window, int line, int col) {
    //     // CLIPABBLE WINDOW
    //     //      -prone to error especially when window have color

    //     int window_len;
    //     int window_col;

    //     if (line + window.Length > 79) {
    //         window_len = window.Length - ((line + window.Length) - 79);
    //     }
    //     else {
    //         window_len = window.Length;
    //     }

    //     if ((col + window[2].Length) > 313) {
    //         window_col = window[2].Length - ((col + window[2].Length) - 313);
    //     }
    //     else {
    //         window_col = window[2].Length - 1;
    //     }

        
       

    //     for (int a = 0; a < window_len; a++) {
    //         Console.SetCursorPosition(col, line);
    //         Console.Write(a <= 2 ? Program.BLACK_ON_WHITE + window[a].Substring(0, window_col) + Program.WHITE_ON_BLACK : window[a].Substring(0, window_col));
    //         line++;
    //     }
        
    //     // UNCLIPABBLE WINDOW

    //     // for(int a = 0;  a < window.Length ; a++) {
    //     //     Console.SetCursorPosition(col, line);
    //     //     Console.WriteLine(window[a]);
    //     //     line++;
    //     // }
    // }


    // public static String[] Window_try = {
    //     @"                                                                                                                                                                                                                     ",
    //     @"                                                                                                                                                                                                                     ",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|                                                                                                                                                                                                                   |",
    //     @"|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|"
    // };
    
    // public static String[] Draw = {
    //     @"|--|",
    //     @"|  |",
    //     @"|--|"
    // };
    
    // public void Screen() {

    //     Console.WriteLine(@"|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|                                                                                                                                                                                                                                                                                                                       |");
    //     Console.WriteLine(@"|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|");

    // }
    

    // public void MHA_Screen() {
    // Console.Clear();
    // cwln.Clear();
    // cwln.Append(@"|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|");
    // cwln.Append(@"|........................................................................................................................................-++++******=...............-#####################:....................................................................................................::.........::::::::::::::|");
    // cwln.Append(@"|.......................................................................................................................................:++++*******=......::.....:*#####################-....................................................................................................:::......:::::::::::::::::|");
    // cwln.Append(@"|......................................................................................................................................:=+++********=......=:....-######################=..........................................................................................................:-:::::::::::::::::::|");
    // cwln.Append(@"|..............................................................................................................-......................:=+++*********=....:++:..:*######################+:......:-:.............................................................................................:::::::::::::::::::::::::|");
    // cwln.Append(@"|..........................................................................................................:..:+-.....................:+++**********=...:+*=.:-######%################+:....:-*-............................................................................................::::::::::::::::::::::::::::|");
    // cwln.Append(@"|.........................................................................................................:+:.:++:...................:++++**********=..:+**::*#####%#################*:...:*#+:...........................................................................................::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|.........................................................................................................:#*:-***:.................:=++++**********=.-***==#####%%%################*:.:*##*:..........................................................................................:::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|.........................................................................................................-##*=****:................:+++++*********+--+***#####%%%%%###############*-=####-........................................................................................:::::::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|.........................................................................................................=#####****-.....:=:...:-.:++++**********+*+***#####%%%%%%%####################+:.....................................................................................:::::::::::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|..........................................................................:::::...............:::........+######****-...:**:..:#=.=+++**********+++***#####%%%%%%%###################*:.................................................................--................:::::::::::::::::::::::::::::::::::::::-:::::|");
    // cwln.Append(@"|........................................................................:.......................-*-......=########*##=..=##-.:##-:++*****++*****++***####%%%%%%%%%##################:................................:...................:+:............=*:.............:::::::::::::::::::::::::::::::::::::::-=::::::|");
    // cwln.Append(@"|..............................................................:--:.............:=+==-::...:-:....:****+=:-############*+####-###-++*************++**###%%%%%%%%%%%%###############=::::--==++++*******##################***+=:.........-+*-....:......:-**+..........::::::::::::::::::::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|................................................................::..............:=*#*++++++*###*+--****#########################=*###*************###%%%%%%%%%%%%%%######################################################+=:......:-+*#**=.....==.....=****:.....::::::::::::::::::::::::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|.................................................................................:=*####***#####################################*####*#**********###%%%%%%%%%#%%%%%#################################################*+-:.:*....:+#######*:....:*+:..:+*****:...::::::::::::::::::::::::::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|..................................................................................:=###################################################****#****##%##%%%%%%%%%%%%%%%#############################################****:...=%=:+#########+....:-##=::=*##****::-++=::::::::::::::::::::::::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|...................................................................................:+###########*##***#*######*#######****#############*###***#####%%%%%%%%%%%%%%%%%#########################################*-::+***-..:#%%%%%%#######=*#%%####+##%%##*#####=:::::::::::::::::::::::::::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|................::..................................................................:+####*****#**********###***#######**#########################%%%%%%%%%%%%%%%%%%%##########################*********#*-:...:+**###:.=%%%%%%%%%####%%%%%%%%%%%%%########-=******++++-:::::::::::::::::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|............:::...............::................................................:=+===##********************#****########**#####################%%%%%%%%%%%%%%%%%%%%%#####################************=:......:***####*-%%%%%%%%%%#%%%%%%%%%%%%%%#######%%%#%%%#########*+=-:::::::::::::::::::::::::::::::::::::::::::|");
    // cwln.Append(@"|...........:+=:.:................::................................................-+*****************************##******###########%#########%%%%%%%%%%%%%%%%%%%%%%%###############*************=:.:=......=***#####%%%##%%%%%%%%%%%%%%%%%%%%#######%%%%%%%%%####%#+::::::::::::::::::::::::::::::::::::::::::::::---|");
    // cwln.Append(@"|.............................::::-:............................................::-+***#*******************************##############%%########%%%%%%%%%%%%%%%%%%%%%%%%%##########*************=:.....:+=:...:+**#####%%%%##%%%%%%%%%%%%%%%%%%#%%###%%%%%%%%%%%%%###****=::::::::::-+*:::::::::::::::::::::::::::::-=**-|");
    // cwln.Append(@"|........................................................................:=++*+***#####********************************############%%%%##**##%%%%%%%%%%%%%%%%%%%%%%%%%%%#######************=:.........:+*+:..:***####%%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##**+++---+####-:::::::::::::::::::::::::::---**--|");
    // cwln.Append(@"|..........................................................................:-**************************************************###%%%%%***#######**#%%%%%%%%%%%%%%%%%%%%####***#********+=--:::........=***-.:*###%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%########-:::::::::::::::::::::::::----------|");
    // cwln.Append(@"|.............................................................................:-+*******************************************####%%%%%%#*#%#***####%%%%%%%%%%%%%%%%%%%%%%######********************+=::.:**##*-*###%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%####-::::::::::::::::::::----------------|");
    // cwln.Append(@"|..........................:....................................................:=###********************************##*****###%%%%%%%%%%#***##%%%#%%%%%%%%%%%%%%%%%%%%%%########**********+=--:........-*#######%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%######%%%%%%%########=::::::::::::::::::--------------------|");
    // cwln.Append(@"|......................:-**+:................................................::=+************************************#########%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%######********++=-:................:*#######%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#####################+-:::::::::::-----=------------------|");
    // cwln.Append(@"|.......................::::..................................................:+**********#********************#####***######%%%%%%%%%%%%%%%%%%#####%%%%%%%%%%%%%%%%%%######****+:........................:=#####%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%#############**+-:::::::::::--------------==------------|");
    // cwln.Append(@"|...........................................................................:+***##**********#%#**#*************############*#%%%%%%%%%%%%%%%#*##***#%%%%%%%%%%%%%%%%%%%%##********-.....................:+#####%%%%%#%%%%%%%%%%%%%%%#%%%%%%##%%%#%%%%%%%%%%%%%%%%%#%######%##**+++-:::::::::---------------------------|");
    // cwln.Append(@"|.........................................................................:===--::=*********#%%%%#*##*****#******##**#########*%%%%%%%%%%%%#########****%%%%%%%%%%%%%%%**#####*******+:....:::......::-+*####%%%%%%###%%%%%%%%%%%%%%%%##%%%%%###%###%%%%%%%%%%%%%%%%%#%%####%%%##*+++-----------------------------------|");
    // cwln.Append(@"|...............................................................................-++*********%%%%%%%%###+*#%******##****#*#######%%%%%%%%%%%%%###################################********=:..:=++++++++**#####%%%####%%%%%%%%%%%%%%%%%%%###%%%####%##%%%%%%%%%%%%%%%%%%%#%%%#########*+=---------------------------------|");
    // cwln.Append(@"|.....................::.....................................................:-==+*****#****%%%%%%#**%%%#*%#******##*****######*#%%%%%%%##########***######################***************+-..:=++*******###%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#######%%%%#%%%%%%%%%%%%%%%%%%%##########**--------------------------------|");
    // cwln.Append(@"|...................:=+:...................................................::.:=+*#**#*****#%%%%#+++#%%%%%%%*******#*****#######*%%%%%%%%#####****#**+-.......:::-==+************************=:.:=*#######%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#####%#%#%##%%%%%#%%%%%%##%%%%%##########**=------------------------------|");
    // cwln.Append(@"|...................:-:......................................................:=+*#*+#**=+++#%%%*+++*%%%%%%%%#*#**+*####***#####**#######%%%#######+:..............................::::-==+******-=+#######%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#####%###%#####%%%####%###%##%%%#***######****---------------------------==|");
    // cwln.Append(@"|...........:-:.............................................................:==:-::##*:.-+=*%#+=+++%%%%%%%%****+*++*#*####*###**##*#******######-:...:::::---:................................:::+**######%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%###%###########%%###*#############*+++++++*****=--------------------------|");
    // cwln.Append(@"|...........:::.............................................................:.....=*-...:++*%#*++#%%#*+#%*+++*+++**+*******##***###**#***####################*=:.............................:::::::=######%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##%############%%##***##############++---===----=--------------------=====|");
    // cwln.Append(@"|................................................................................--...:-+***#####**++++*++++++++++++*********+#######**###################*****+:.........................:::::::::+########%%%%%%%%%%%%%%%%%%%%%###%%%%%%%%%%%##################****##############*+=---------------------------=======|");
    // cwln.Append(@"|...................................................................................=*+++++++++++++++*#*++++++++++++++***#%%########################*************-....................:::::::::::-****#######%%%%##%%%%%%%%%%%%#####%%%%%%%%%%%############**###******##*******###*##+-------------------------=========|");
    // cwln.Append(@"|..........:=::.....................................................................:+++++++++++++*+++++*#+++++++++++++**########################*********#*******-...............::::::::::::::+****#######%%%%%%%%%%%%%%%%######%%%%%%%%%%%%%###%###***#***###*******#*************#+---------------------============|");
    // cwln.Append(@"|....................................................................................:=+++++++++=====+*###*++++++++++++**##################%%###*********###*****++-.............::::::::::::=+***#########%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#######**#*****#*********#**************=------------------==============|");
    // cwln.Append(@"|......................................................................................-+++++=====***######++++++++++++*####**#################*********####*##***++=.........::::::::::::::::-+##########%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%#########**##*****#****#**####************++*=--------------================|");
    // cwln.Append(@"|......................................................................................:==+====***#########++++++++++++*#*******##############*********#####*%@*****=:....::::::::::::::::::::::::+**#######%#%%#####%%%%%%%%%%%%%%%%%%%%%%#########***#*****#%*******####**++++***********+=--------===================|");
    // cwln.Append(@"|........................................................................................::=+++############+===+++++++**************#########**********######******##*+++*****+++==-::::::::::::=***####%%%#####%%%%%%%%%%%%%%%%%%%%%%%%%%#######%#***##****#*#***#**#*###**+++++*++++********+=========================|");
    // cwln.Append(@"|..............................................................................................:+##########+=======++****************#######**********#######*****#############**++++==::::::::+*+==+####%%%%%%%%%%%%%%%%%%%%%%%#%%%%%################%#**#**#***#####**##*+++++++++----=++=--------====================|");
    // cwln.Append(@"|................................................................................................-#########=========+*********++********####*********#*######****##################*+====::::::::::=###%%%%%%%%%%%%%%%%%%%%%%%%###%%#########%##**#####**#**#**+###*###**#*+*****==+++------=*+=--======================|");
    // cwln.Append(@"|.................................................................................................:+######*========+#********++++**+++****#**************#@###***###############*******===-::::::::+******#%%%%%%%%%%%%%%%%%%%%##%%######%###******####*#++*#+*##**#*##****+***##*#*===++--=*+==========================|");
    // cwln.Append(@"|..................................................................................................:+#*+=+========##********++++++*++++++*****************##***#%#######******************++=---=++****####%%%%%%%%%%%%%%%%%%%%%#%%##%####*********#%**#++**+*#*+*****##*+*+****+*#**=-----=============================|");
    // cwln.Append(@"|..................................................................................................:----========#%*********++++++++++++++**********************%%#**********************%%%%%%%%#**++==-*###%#%%%%%%%%%%%%%%%%%####*******##***+++**#*+*++++++++%%##%%**+++++#**++**==+=--==============================|");
    // cwln.Append(@"|..................................................................................................-===-----===:.:===++++++++++++++++++++*********************#%%#*********++++*********%%%%%%%%%%%%%########%%%%%####%%%%%%%%%**##+*#%%%%%%%%*+++++++++++++++##+++++%#-=--==+***+**====================================|");
    // cwln.Append(@"|..................................................................................................-===----=-..::+===+++**#*==++++++++++**************#******#%%%#*****+++++++++++++****%%%%%%%%%%%%%##%##%###%%%#*######%%%#%**+**%%#%%#++++++%#*++++++++++#%%%#====*#:+*-:-=*+****+===================================|");
    // cwln.Append(@"|....................................................................................................-----::::::+==++++********++++++++***************%%*****%%%%#****+++++++++++++++***#%%%%%%%%%%%%###%####%%%%#*##%####%##%*++*%**#%%#+++++++*#**++++++++*****====*+=+++--:===-+*#===================================|");
    // cwln.Append(@"|........................................................................:::::........................:::::::::+++++++**********+++++++******+++************%%%%%%#***+++++++++++*##%%*###%%%%%%%%%%%####%#######%**%###*#####+++##++*+*#=======++++++++++++==++==--=*=++*=---======++==================================|");
    // cwln.Append(@"|......................................................................::::::::........................:::::::-++++++*+*********##++++++========+**********#%%%%%%%**+++++++++++*##########%%%%%%%%%%##############***#*****#%+++#+++++++++=====+++++++++++====-----=:=**=++=--=========================================|");
    // cwln.Append(@"|........................................................:::::::::::.:::::::::::....:::::::::.......:::::::::-+++++++++++*******%+*+=++++===*#+===*********%%%%%%%%#*+++++++++++######%#########%%%%%################*##*******+++*++++=========++++++++++====----==:-++++=++++=========================================|");
    // cwln.Append(@"|........................................................:::::::::::::::::::::::::::::::::::::::::.::::::::--===----=+++++++****+++++==++=--=+=====*+*****#%%%%%%%%%#++++++++++*######%%###%%%%#####%%###########%%#%#******+++++++*++==========++++++++++======----:+++++++++++++======================================|");
    // cwln.Append(@"|......................................................::::::::::::::::::::::::::::::::::::::::::::::::::--:::--------+++++++++*+++++====+=--------=******#%%%%%%%%%%*+++++++++#*######%%%%%%%%%%%%###%%######%%%%%%%%%#####*+++++++++++++++++++++++++=+++====-----:-**++++++++++++=====================================|");
    // cwln.Append(@"|.....................................................::::::::::::::::::::::::::::::::::::::::::::::::::--::::---=#-:-=+++++++**++=-=+====+----*#---=*****%%%%%%%%%%%%**++++++**#############%%%%%%%%####%%%%%%%%%#%%%%#***##*++++++++++++++++++++===========-----::+****+++++++++++++==================================|");
    // cwln.Append(@"|.....................................................:::::::::::::::-----:::::::::::::::::::::::::::::::::::::=-::::::-++++++**#++==========---+----=++**#%%%%%%%%%%%%*****++*#############%%%%%%%%%%%##%%%%%%%%%%%%%%%#****#*++++++++++++++===============-----::*********++++++++++++================================|");
    // cwln.Append(@"|.....................................................:::::::::::::---------------::::-::--:--::-:::::::::::::::=-::=-::=*++++#**#*==-------=-:::-=----+++#%%%#%%%%%%%%%#******####%%%%#########%%%%%%%%%%%%%%%%%%%%%%%%%#*#***#*+++++++++=================+=---::************+++++++++++++=============================|");
    // cwln.Append(@"|......................................................:::--------=-:-====------------------------:::::::::::::::=-:-+:::-++++******=---------=::-*#---=+****#############%%###%%#################%%%%%%%%%%%%%%%%##%%#%%%%#*****#*++====+*+++++======++===----:+***###*#***###*++++++++++++++==========================|");
    // cwln.Append(@"|......................................................::---====================-----------------:::::::::::::----==:::::::*++****+++=--------+++++++++**############%%###%%%%%%%%######%%%####**##%%%%%%%%%%##########%%%%%##******#+====================---:+**********#########++++++********+===================--:-|");
    // cwln.Append(@"|...............:.......................:-............:::--====================----------------::::::::::::::------==::*+:::++:#**+++++-----=++++****##############################%########**********#%%%%%%%%%%%%%%%##*%%%%%%%#*****#*+=================-=*#==*#####**++##########*********++++++===============--===+|");
    // cwln.Append(@"|..............:=:....................::::...........::::-===================---------------::::::::::::::::-======--=------:-:-##+++==++-=****#################**************############***#####********###%%%%%%%%%%****#%%%%%%%%#######%#*+=======+**+###*==*******####+*#####%%%#**+++++++++++++==========--====+++|");
    // cwln.Append(@"|............:.::....................................:::--==================-----------::::::::::::::::::::-======---------::::::*#++==+****#################*******************#######%%%%%#####************######%%%#+*******#%%%%%%%%%%%#%*######*****+=+#+=-**********#****##%%%%%##****++++++++++=======--===++++++|");
    // cwln.Append(@"|............::..................................:::::::--================-------------::::::::::::::::::--=======----------::::::=**+#########################********************##%%%%%%%%%##***************#######%#*+#*++*****#%%%%%##%%****#********===---*****+******+-=+*##%%#######**++++++++++====-==+++++++++|");
    // cwln.Append(@"|.............................................::::::::::--===============------------::::::::::::::::::----======----------:::-=+###*******++**+==***+=+****#####****************#%%%%%%%%%%%%%%***********+++++**######%%#++**+*******###%%%*************=*%::-****++*****++#*==+##########**+++++++++***====++++++++++|");
    // cwln.Append(@"|..........................................::::::::::::----============-------------::::::::::::::::::------=====------:=*#+++**##*+++***+=============+*****######***********###%%%%%%%%%%%%%##%#*****++++++++++++*#######*+++***++++*******#******%#****===::=+======++*+=*###*=-+*****##***++++++++*****-=+++++++++++|");
    // cwln.Append(@"|........................................::::::::::::------============------------:::::::::::::::::-----------------*###==+#############*+============+**######################%%%%%%%%%%%%%%%%%%#**++++++++++=====+*######+++*++++++*++*****************==+:------------:::-=*#*+-=+*****+====++++*****+++##++++++++++|");
    // cwln.Append(@"|......................................:::::::::::::--------==========-----------:::::::::::::::::::--------------:-***##-:::=##############+====-=-==+*#######################%%%%%%%%%%%%%%%%%%%%#*++++++++=========+*######*+++===++++****#++++**%#****++*+*****+++++====-::---++--+===--=+***********######+++++++++|");
    // cwln.Append(@"|.................:::.............::::::::::::::::-----------=========----------::::::::::::::::::::----------==+**********=:::+#######%%%%%%#=+-=++==+*######################%%%%%%%%%%%%%%%%%%%%%%**+++++=============**##*###*+===+=----+*#++++++****+*+++*##***++===+******=--====--=+==+***********####**=-++++++++|");
    // cwln.Append(@"|...............................::::::::::-----:::-------::---=======---------::::::::::::::::::::::-----=+++************++++=::=%%%%%%%%%%%##*-=+++++=-+*###**##*##########*#%%%%%%%%%%%%%%%%%%%%%%#*++===============+**%%##****#*+=-----:+--=+++++++++++=**#****+++++*********+=======***++*****+=-=++=+=====-+++++++|");
    // cwln.Append(@"|.............................::::::::::---------::----:::::-=======--------::::::::::::::::::::::::---========+*+***+++++++===+%%##########*=+##%*++++=====**###*#########*##%%%%%%%%%%%%%%%%%%%%%%%*+===============++**%%%#%###**#=-----==:-----====++==***#****+++++++***********=---+****++=====+++========-=++++++|");
    // cwln.Append(@"|............................:::::::::::----------::---::::--======----------::::::::::::::::::::::::-==++++**+-=+++=++++=======*-:+######*++#####%#=+++++++++*############*#%%%%%%%%%%%%%%%%%%%%%%%%#+=============+++*%%%%%%######%#+=--=+------======++####*#***++***++++***********===+*===--=======+#*##+=--=++++++|");
    // cwln.Append(@"|.........................::::::::::::::---------:::::::::--=====--------------:::::::::::::::::=##+-==++++*####+-=+++=========---::+###**=*#######%#=+++++++++++*########**#%#%%%%%%%%%%%%%%%%%%%%%%#*===+======+++*#%%%%%%%%%%#######%###+=----=+====*#%%###***#*++++++***************++==+--=========+#*#*+---=++++++|");
    // cwln.Append(@"|.....................::::::::::::::::::---------::::::------=-----------------::::::::::::::::-###*+++++**#######=:========-----:-::+##=+############+*#++++++++++**#####*##%%%%%%%%%%%%%%%%%%%%%%%%%*=+===+++++*#%%%%%%%%%%%%########%#########**++*%%%%%%#####*++*+++****###**++++****+============-----==---==++++++|");
    // cwln.Append(@"|:.::::::::.::::.:::::::::::::::::::::::--------::::::-------------------------:::::::::::::::-=#*++++++*##########=:=------------:-::==*###############*##*+++++++****###*#%%%%%%%%%%%%%%%%%%%%%%%%%%#+=++*++#%%%%%%%%%%%%%%%#####################%%%%%%%%%%%#####******+*##*==*#**+=++==+++++======---------=+++++++++|");
    // cwln.Append(@"|::::::::::::::::::::::::::::::::::::::::--::::::::::--------------------------+%###-::::-==----++++===+**##########+:----------::::-::*########*****########*++++*********#%%%%%%%%%%%%%%%%%%%%%%%%%%*+=+#%%%%%%%%%%%%%%%#######################%%%%%%%%%%%%%%#####****++**=*##+#*#**####*=+*+=====-------=++++++++++++|");
    // cwln.Append(@"|::::::::::::::::::::::::::::::::::::::::::::::::::::-------------------------+##+***+=---=+****+++======++****######+:::------------:::#######*******##########*++=+******#%%%%%%%%%%%%%%%%%%%%%%%%%#+++++*#%%%%%%%%%%%%#######################%%%%%%%%%%%%%%%%#####****#*+*#%%%%%%%#######+**+=====---++++++++++++++++|");
    // cwln.Append(@"|::::::::::::::::::::::::::::::::::::-::::::::-::::::-------------------------*##+++***********++++++++++++++*#***####=:::------===--=-:-##*****####################*******#%%%%%%%%%%%%%%%%%%%%%%%%#==++++++++********########################%%%%%%%%%%%%%%%%%%%%####**#+##%%%%%%%%#######*+*+=====+++++++++++++++++++|");
    // cwln.Append(@"|:::::::::::::::::::::::::::::::::::::::::::::--::::::---:---------------=====*#**+++*********++++=====++***********###=:=-=======-::--=*#########*********#############**#%%%%%%%%%%%%%%%%%%%%%%%%#===+++++++++====+++*#####################%%%%%%%%%%%%%%%%%%%%######**=++=+#%%%%%#########+=+==++++++++++++++++++++++|");
    // cwln.Append(@"|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|");
    // Console.WriteLine(cwln);
    // cwln.Clear();
    // //Use String Builder to make it load faster
    // }
    

}